# Generated by Django 5.2.16 on 2026-07-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_task_project_project_due_date_task_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('On Hold', 'On Hold')], default='Active', max_length=20),
        ),
    ]
