# Generated by Django 5.2.16 on 2026-07-16 08:50

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_task_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='is_temp_password',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contributor',
            name='joined_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='contributor',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contributor',
            name='security_answer_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contributor',
            name='security_answer_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contributor',
            name='security_answer_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='skills',
            field=models.TextField(blank=True, help_text='Skills represented as plain text, comma-separated list, or JSON string.', null=True),
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_answer_1', models.CharField(blank=True, max_length=255, null=True)),
                ('security_answer_2', models.CharField(blank=True, max_length=255, null=True)),
                ('security_answer_3', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
